name: 'build-uploader'
description: 'Upload a build to Treasure'
author: 'Treasure <engineering@treasure.lol>'
inputs:
  api-key:
    description: 'Treasure API key'
    required: true
  api-base-url:
    description: 'Treasure API base URL'
    required: true
  game-id:
    description: 'Game ID'
    required: true
  windows-build-path:
    description: 'Path to Windows build'
    required: false
  macos-build-path:
    description: 'Path to macOS build'
    required: false
outputs:
  build-id:
    description: 'Build ID'
runs:
  using: 'node20'
  main: 'dist/index.js'
