name: Release
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Create release PR
        uses: changesets/action@v1
        with:
          version: pnpm package:version
          publish: pnpm package:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
